import type { Metadata } from "next"

import { fontSans } from "@/lib/fonts"
import { cn } from "@/lib/utils"

import "./globals.css"

import { Footer } from "@/components/footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          fontSans.variable,
          "bg-background font-sans font-normal  text-foreground"
        )}
      >
        {/* TODO: Header */}
        {children}
        <Footer />
      </body>
    </html>
  )
}
