import { Reference } from "@/types"

export const REFERENCES_PER_PAGE = 9

export const references: Reference[] = [
  {
    category: "Design",
    image: "/images/reference-1.png",
    label: "SOFA",
    url: "/portfolio/sofa",
  },
  {
    category: "Branding",
    image: "/images/reference-2.png",
    label: "KeyBoard",
    url: "/portfolio/keyboard",
  },
  {
    category: "Illustration",
    image: "/images/reference-3.png",
    label: "Work Media",
    url: "/portfolio/work-media",
  },
  {
    category: "Motion",
    image: "/images/reference-4.png",
    label: "DDDone",
    url: "/portfolio/dddone",
  },
  {
    category: "Design",
    image: "/images/reference-5.png",
    label: "Abstract",
    url: "/portfolio/abstract",
  },
  {
    category: "Branding",
    image: "/images/reference-6.png",
    label: "HandP",
    url: "/portfolio/handp",
  },
  {
    category: "Motion",
    image: "/images/reference-7.png",
    label: "Architect",
    url: "/portfolio/architect",
  },
  {
    category: "Design",
    image: "/images/reference-8.png",
    label: "CalC",
    url: "/portfolio/calc",
  },
  {
    category: "Branding",
    image: "/images/reference-9.png",
    label: "Sport",
    url: "/portfolio/sport",
  },
  {
    category: "Design",
    image: "/images/reference-1.png",
    label: "SOFA 2",
    url: "/portfolio/sofa-2",
  },
  {
    category: "Branding",
    image: "/images/reference-2.png",
    label: "KeyBoard 2",
    url: "/portfolio/keyboard-2",
  },
  {
    category: "Illustration",
    image: "/images/reference-3.png",
    label: "Work Media 2",
    url: "/portfolio/work-media-2",
  },
  {
    category: "Motion",
    image: "/images/reference-4.png",
    label: "DDDone 2",
    url: "/portfolio/dddone-2",
  },
  {
    category: "Design",
    image: "/images/reference-5.png",
    label: "Abstract 2",
    url: "/portfolio/abstract-2",
  },
  {
    category: "Branding",
    image: "/images/reference-6.png",
    label: "HandP 2",
    url: "/portfolio/handp-2",
  },
  {
    category: "Motion",
    image: "/images/reference-7.png",
    label: "Architect 2",
    url: "/portfolio/architect-2",
  },
  {
    category: "Design",
    image: "/images/reference-8.png",
    label: "CalC 2",
    url: "/portfolio/calc-2",
  },
  {
    category: "Branding",
    image: "/images/reference-9.png",
    label: "Sport 2",
    url: "/portfolio/sport-2",
  },
  {
    category: "Design",
    image: "/images/reference-1.png",
    label: "SOFA 3",
    url: "/portfolio/sofa-3",
  },
  {
    category: "Branding",
    image: "/images/reference-2.png",
    label: "KeyBoard 3",
    url: "/portfolio/keyboard-3",
  },
  {
    category: "Illustration",
    image: "/images/reference-3.png",
    label: "Work Media 3",
    url: "/portfolio/work-media-3",
  },
  {
    category: "Motion",
    image: "/images/reference-4.png",
    label: "DDDone 3",
    url: "/portfolio/dddone-3",
  },
  {
    category: "Design",
    image: "/images/reference-5.png",
    label: "Abstract 3",
    url: "/portfolio/abstract-3",
  },
  {
    category: "Branding",
    image: "/images/reference-6.png",
    label: "HandP 3",
    url: "/portfolio/handp-3",
  },
  {
    category: "Motion",
    image: "/images/reference-7.png",
    label: "Architect 3",
    url: "/portfolio/architect-3",
  },
  {
    category: "Design",
    image: "/images/reference-8.png",
    label: "CalC 3",
    url: "/portfolio/calc-3",
  },
  {
    category: "Branding",
    image: "/images/reference-9.png",
    label: "Sport 3",
    url: "/portfolio/sport-3",
  },
  {
    category: "Design",
    image: "/images/reference-1.png",
    label: "SOFA 4",
    url: "/portfolio/sofa-4",
  },
  {
    category: "Branding",
    image: "/images/reference-2.png",
    label: "KeyBoard 4",
    url: "/portfolio/keyboard-4",
  },
  {
    category: "Illustration",
    image: "/images/reference-3.png",
    label: "Work Media 4",
    url: "/portfolio/work-media-4",
  },
  {
    category: "Motion",
    image: "/images/reference-4.png",
    label: "DDDone 4",
    url: "/portfolio/dddone-4",
  },
  {
    category: "Design",
    image: "/images/reference-5.png",
    label: "Abstract 4",
    url: "/portfolio/abstract-4",
  },
  {
    category: "Branding",
    image: "/images/reference-6.png",
    label: "HandP 4",
    url: "/portfolio/handp-4",
  },
  {
    category: "Motion",
    image: "/images/reference-7.png",
    label: "Architect 4",
    url: "/portfolio/architect-4",
  },
  {
    category: "Design",
    image: "/images/reference-8.png",
    label: "CalC 4",
    url: "/portfolio/calc-4",
  },
  {
    category: "Branding",
    image: "/images/reference-9.png",
    label: "Sport 4",
    url: "/portfolio/sport-4",
  },
]
